#!/bin/bash
# SPDX-FileCopyrightText: 2023 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

export UNIVENTION_KEYCLOAK_BOOTSTRAP_DEBUG_PAUSE_BEFORE_SCRIPT_START=${UNIVENTION_KEYCLOAK_BOOTSTRAP_DEBUG_PAUSE_BEFORE_SCRIPT_START:-}
export UNIVENTION_KEYCLOAK_BOOTSTRAP_TEMP_DIR=${UNIVENTION_KEYCLOAK_BOOTSTRAP_TEMP_DIR:-}

# Optional Debug-Pause
regex_check_int='^[0-9]+$'
if [[ ${UNIVENTION_KEYCLOAK_BOOTSTRAP_DEBUG_PAUSE_BEFORE_SCRIPT_START} =~ ${regex_check_int} ]] ; then
  echo "Pausing ${UNIVENTION_KEYCLOAK_BOOTSTRAP_DEBUG_PAUSE_BEFORE_SCRIPT_START} seconds before starting the script."
  sleep "${UNIVENTION_KEYCLOAK_BOOTSTRAP_DEBUG_PAUSE_BEFORE_SCRIPT_START}"
fi

# Start the bootstrapping
export ANSIBLE_HOME=${UNIVENTION_KEYCLOAK_BOOTSTRAP_TEMP_DIR}
export ANSIBLE_REMOTE_TMP=${UNIVENTION_KEYCLOAK_BOOTSTRAP_TEMP_DIR}
cd /app/ansible-base || exit 1
ansible-playbook -v main.yml
