#!/bin/sh
# shellcheck disable=SC2016
set -e -u

exec >generated-config-doc.yml
cat "${0%/*}/base-doc.yml"

doc_job () { # <extends> [<suffix> [<language>]]
    echo
    echo "build ${pkg}${3:+ "$3"}${2:+ "$2"}:"
    echo '  variables:'
    echo "    DOCS_DIR: $path"
    echo "    DOC_TARGET_NAME: ${path##*/}"
    if [ "$pkg" = "keycloak-app" ]
    then
        echo -n '    DOC_TARGET_PATH: "$DOC_TARGET_NAME/'
        echo '$DOC_TARGET_VERSION"'
    fi
    [ -n "${3+empty}" ] && echo "    language: $3"

    echo "  extends: ${1:?extends}"
    echo '  rules:'
    echo '    - changes:'
    echo "      - ${path}/**/*"
    echo '      - docs/abbreviations.txt'
    echo '      - docs/bibliography.bib'
    echo '      - docs/links.txt'
}

document_paths () {
    for p in docs/*/conf.py
    do
        [ -f "$p" ] || continue
        path="${p%/conf.py}"
        echo "      - $path/**/*"
    done
}

merge_one_artifact () {
    echo
    echo 'docs-merge-to-one-artifact:'
    echo '  extends: .docs-merge'
    echo '  rules:'
    echo '    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
    echo '      changes:'
    document_paths
    echo '    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    echo '      changes:'
    document_paths
    echo '      when: manual'
}

review_job () {
    echo
    echo 'review:'
    echo '  extends: .sphinx-review-template'
    echo '  needs:'
    echo '    - job: docs-merge-to-one-artifact'
    echo '  rules:'
    echo '    - changes:'
    document_paths
}

create_production_merge_request () {
    echo
    echo 'docs-create-production-merge-request:'
    echo '  extends: .sphinx-docs-merge-request-template'
    echo '  needs:'
    echo '    - job: docs-merge-to-one-artifact'
    echo '  rules:'
    echo '    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    echo '      changes:'
    document_paths
}

for make in docs/*/Makefile
do
    [ -f "$make" ] || continue
    path="${make%/Makefile}"
    pkg="${path##*/}"

    # Automatically detect Sphinx or Docbook
    if [ -f "${path}/conf.py" ] # Use Sphinx's conf.py as hint to Sphinx
    then
        for l_path in "$path"/locales/* "en"
        do
            language="${l_path##*/}"
            [ "$language" = '*' ] && continue

            doc_job '.sphinx-html-template' html "$language"
            doc_job '.sphinx-pdf-template' pdf "$language"
            doc_job '.sphinx-linkcheck-template' linkcheck "$language"
            doc_job '.sphinx-spelling-template' spelling "$language"
        done
    fi
done
merge_one_artifact
review_job
create_production_merge_request
