#!/bin/bash
#
# App join script
#
# Copyright 2021 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

## joinscript api: bindpwdfile

VERSION="1"

. /usr/share/univention-join/joinscripthelper.lib
. /usr/share/univention-lib/all.sh

joinscript_init

app_id="keycloak"

ucs_addServiceToLocalhost "$app_id" "$@"

domainname="$(ucr get domainname)"
hostname="$(ucr get hostname)"

url_prefix="$(ucr get keycloak/url/prefix)"
if [ -n "$url_prefix" ]; then
    univention-add-vhost "$url_prefix.$hostname.$domainname" 443 \
	--conffile /var/lib/univention-appcenter/apps/$app_id/config/vhost.conf "$@"
    service apache2 reload
fi

COMPONENT_ID=$(univention-app get $app_id component_id | cut -f 2 -d ':' | tr -d '[:space:]')
ucr set \
  ucs/web/overview/entries/admin/$app_id/description/de="Keycloak" \
  ucs/web/overview/entries/admin/$app_id/description="Keycloak" \
  ucs/web/overview/entries/admin/$app_id/label="Keycloak" \
  ucs/web/overview/entries/admin/$app_id/link="https://keycloak.$hostname.$domainname/" \
  ucs/web/overview/entries/admin/$app_id/icon="/univention/js/dijit/themes/umc/icons/scalable/apps-$COMPONENT_ID.svg" \
  ucs/web/overview/entries/admin/$app_id/link-target='newwindow'

univention-keycloak-config "$@"

joinscript_save_current_version

exit 0