#!/bin/bash

set -e

# create password
pwdfile="/etc/keycloak.secret"
[ -e "$pwdfile" ] || makepasswd --chars 20 > "$pwdfile"

# install jq TODO remove
command -v jq || {
    apt-get -qq update
    apt-get -qq -y install jq
}