/*
 * Univention Directory Manager REST interface
 * Schema definition for the objects in the Univention Directory Manager REST interface
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Policies which apply for this object.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-25T19:07:57.795532733+01:00[Europe/Madrid]", comments = "Generator version: 7.9.0")
public class UsersUserPolicies {
  public static final String SERIALIZED_NAME_POLICIES_DESKTOP = "policies/desktop";
  @SerializedName(SERIALIZED_NAME_POLICIES_DESKTOP)
  private List<String> policiesDesktop = new ArrayList<>();

  public static final String SERIALIZED_NAME_POLICIES_PWHISTORY = "policies/pwhistory";
  @SerializedName(SERIALIZED_NAME_POLICIES_PWHISTORY)
  private List<String> policiesPwhistory = new ArrayList<>();

  public static final String SERIALIZED_NAME_POLICIES_UMC = "policies/umc";
  @SerializedName(SERIALIZED_NAME_POLICIES_UMC)
  private List<String> policiesUmc = new ArrayList<>();

  public UsersUserPolicies() {
  }

  public UsersUserPolicies policiesDesktop(List<String> policiesDesktop) {
    this.policiesDesktop = policiesDesktop;
    return this;
  }

  public UsersUserPolicies addPoliciesDesktopItem(String policiesDesktopItem) {
    if (this.policiesDesktop == null) {
      this.policiesDesktop = new ArrayList<>();
    }
    this.policiesDesktop.add(policiesDesktopItem);
    return this;
  }

  /**
   * Policy: Desktop
   * @return policiesDesktop
   */
  @javax.annotation.Nullable
  public List<String> getPoliciesDesktop() {
    return policiesDesktop;
  }

  public void setPoliciesDesktop(List<String> policiesDesktop) {
    this.policiesDesktop = policiesDesktop;
  }


  public UsersUserPolicies policiesPwhistory(List<String> policiesPwhistory) {
    this.policiesPwhistory = policiesPwhistory;
    return this;
  }

  public UsersUserPolicies addPoliciesPwhistoryItem(String policiesPwhistoryItem) {
    if (this.policiesPwhistory == null) {
      this.policiesPwhistory = new ArrayList<>();
    }
    this.policiesPwhistory.add(policiesPwhistoryItem);
    return this;
  }

  /**
   * Policy: Passwords
   * @return policiesPwhistory
   */
  @javax.annotation.Nullable
  public List<String> getPoliciesPwhistory() {
    return policiesPwhistory;
  }

  public void setPoliciesPwhistory(List<String> policiesPwhistory) {
    this.policiesPwhistory = policiesPwhistory;
  }


  public UsersUserPolicies policiesUmc(List<String> policiesUmc) {
    this.policiesUmc = policiesUmc;
    return this;
  }

  public UsersUserPolicies addPoliciesUmcItem(String policiesUmcItem) {
    if (this.policiesUmc == null) {
      this.policiesUmc = new ArrayList<>();
    }
    this.policiesUmc.add(policiesUmcItem);
    return this;
  }

  /**
   * Policy: UMC
   * @return policiesUmc
   */
  @javax.annotation.Nullable
  public List<String> getPoliciesUmc() {
    return policiesUmc;
  }

  public void setPoliciesUmc(List<String> policiesUmc) {
    this.policiesUmc = policiesUmc;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsersUserPolicies usersUserPolicies = (UsersUserPolicies) o;
    return Objects.equals(this.policiesDesktop, usersUserPolicies.policiesDesktop) &&
        Objects.equals(this.policiesPwhistory, usersUserPolicies.policiesPwhistory) &&
        Objects.equals(this.policiesUmc, usersUserPolicies.policiesUmc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(policiesDesktop, policiesPwhistory, policiesUmc);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsersUserPolicies {\n");
    sb.append("    policiesDesktop: ").append(toIndentedString(policiesDesktop)).append("\n");
    sb.append("    policiesPwhistory: ").append(toIndentedString(policiesPwhistory)).append("\n");
    sb.append("    policiesUmc: ").append(toIndentedString(policiesUmc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("policies/desktop");
    openapiFields.add("policies/pwhistory");
    openapiFields.add("policies/umc");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UsersUserPolicies
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UsersUserPolicies.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UsersUserPolicies is not found in the empty JSON string", UsersUserPolicies.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UsersUserPolicies.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UsersUserPolicies` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("policies/desktop") != null && !jsonObj.get("policies/desktop").isJsonNull() && !jsonObj.get("policies/desktop").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `policies/desktop` to be an array in the JSON string but got `%s`", jsonObj.get("policies/desktop").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("policies/pwhistory") != null && !jsonObj.get("policies/pwhistory").isJsonNull() && !jsonObj.get("policies/pwhistory").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `policies/pwhistory` to be an array in the JSON string but got `%s`", jsonObj.get("policies/pwhistory").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("policies/umc") != null && !jsonObj.get("policies/umc").isJsonNull() && !jsonObj.get("policies/umc").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `policies/umc` to be an array in the JSON string but got `%s`", jsonObj.get("policies/umc").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UsersUserPolicies.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UsersUserPolicies' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UsersUserPolicies> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UsersUserPolicies.class));

       return (TypeAdapter<T>) new TypeAdapter<UsersUserPolicies>() {
           @Override
           public void write(JsonWriter out, UsersUserPolicies value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UsersUserPolicies read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UsersUserPolicies given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UsersUserPolicies
   * @throws IOException if the JSON string is invalid with respect to UsersUserPolicies
   */
  public static UsersUserPolicies fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UsersUserPolicies.class);
  }

  /**
   * Convert an instance of UsersUserPolicies to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

