/*
 * Univention Directory Manager REST interface
 * Schema definition for the objects in the Univention Directory Manager REST interface
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.UsersUser;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * UsersUserListEmbedded
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-25T19:07:57.795532733+01:00[Europe/Madrid]", comments = "Generator version: 7.9.0")
public class UsersUserListEmbedded {
  public static final String SERIALIZED_NAME_UDM_COLON_OBJECT = "udm:object";
  @SerializedName(SERIALIZED_NAME_UDM_COLON_OBJECT)
  private List<UsersUser> udmColonObject = new ArrayList<>();

  public UsersUserListEmbedded() {
  }

  public UsersUserListEmbedded udmColonObject(List<UsersUser> udmColonObject) {
    this.udmColonObject = udmColonObject;
    return this;
  }

  public UsersUserListEmbedded addUdmColonObjectItem(UsersUser udmColonObjectItem) {
    if (this.udmColonObject == null) {
      this.udmColonObject = new ArrayList<>();
    }
    this.udmColonObject.add(udmColonObjectItem);
    return this;
  }

  /**
   * Get udmColonObject
   * @return udmColonObject
   */
  @javax.annotation.Nullable
  public List<UsersUser> getUdmColonObject() {
    return udmColonObject;
  }

  public void setUdmColonObject(List<UsersUser> udmColonObject) {
    this.udmColonObject = udmColonObject;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsersUserListEmbedded usersUserListEmbedded = (UsersUserListEmbedded) o;
    return Objects.equals(this.udmColonObject, usersUserListEmbedded.udmColonObject);
  }

  @Override
  public int hashCode() {
    return Objects.hash(udmColonObject);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsersUserListEmbedded {\n");
    sb.append("    udmColonObject: ").append(toIndentedString(udmColonObject)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("udm:object");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UsersUserListEmbedded
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UsersUserListEmbedded.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UsersUserListEmbedded is not found in the empty JSON string", UsersUserListEmbedded.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UsersUserListEmbedded.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UsersUserListEmbedded` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("udm:object") != null && !jsonObj.get("udm:object").isJsonNull()) {
        JsonArray jsonArrayudmColonObject = jsonObj.getAsJsonArray("udm:object");
        if (jsonArrayudmColonObject != null) {
          // ensure the json data is an array
          if (!jsonObj.get("udm:object").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `udm:object` to be an array in the JSON string but got `%s`", jsonObj.get("udm:object").toString()));
          }

          // validate the optional field `udm:object` (array)
          for (int i = 0; i < jsonArrayudmColonObject.size(); i++) {
            UsersUser.validateJsonElement(jsonArrayudmColonObject.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UsersUserListEmbedded.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UsersUserListEmbedded' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UsersUserListEmbedded> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UsersUserListEmbedded.class));

       return (TypeAdapter<T>) new TypeAdapter<UsersUserListEmbedded>() {
           @Override
           public void write(JsonWriter out, UsersUserListEmbedded value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UsersUserListEmbedded read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UsersUserListEmbedded given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UsersUserListEmbedded
   * @throws IOException if the JSON string is invalid with respect to UsersUserListEmbedded
   */
  public static UsersUserListEmbedded fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UsersUserListEmbedded.class);
  }

  /**
   * Convert an instance of UsersUserListEmbedded to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

