#!/bin/bash

exec 3<>/dev/tcp/localhost/8180
echo -e "GET / HTTP/1.1\nhost: localhost:8180\n" >&3
timeout --preserve-status 1 cat <&3 | grep -q "Welcome to Keycloak"
ERROR=$?
exec 3<&-
exec 3>&-
exit $ERROR
