#!/bin/bash
# if missing, append / to $KEYCLOAK_SERVER_SSO_PATH
# https://www.keycloak.org/observability/health#_healthcheck
URI="${KEYCLOAK_SERVER_SSO_PATH%/}/"
{ printf "HEAD ${URI}health/ready HTTP/1.0\r\n\r\n" >&0; grep 'HTTP/1.0 200'; } 0<>/dev/tcp/localhost/9000
