# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2025 Univention GmbH
---

global:
  imagePullPolicy: "IfNotPresent"
image:
  registry: "registry.kyverno.test"
  pullPolicy: "kyverno"
  tag: "0.0.1@sha256:d0f02b847daad4cae834bcd29266ba30bfc806034a9aac2811e3f66bfd6ecec8"

...
